# Disable the blank line at the start of the prompt
add_newline = false

[username]
disabled = false
show_always = true
style_user = "#c6a0f6"
style_root = "#ed8796"

[character]
success_symbol = "[â®](bold #c6a0f6) "
error_symbol = "[â®](bold #ed8796) "

[directory]
format = "[$path](#a6da95)[$read_only]($read_only_style) "
truncation_length = 3
home_symbol = "~"
read_only_style = "#ed8796"

[docker_context]
format = 'via [ğŸ‹ $context](#8aadf4 bold)'

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold #ed8796)'

[git_metrics]
added_style = 'bold #8aadf4'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](#a6da95)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
style = "#cad3f5"

[dart]
format = 'via [ğŸ¯ $version](bold #ed8796) '

[java]
symbol = 'â˜• '
style = "bold #ed8796"

[kotlin]
symbol = 'ğŸ…º '
style = "bold #f5a97f	"

[lua]
format = 'via [ğŸŒ™ $version](bold #8aadf4) '

[nodejs]
format = 'via [îœ˜ $version](bold #a6da95) '

[package]
format = 'via [ğŸ $version](bold) '

[python]
symbol = 'ğŸ '
style = "bold #eed49f"

[ruby]
symbol = 'ğŸ’ '
style = "bold #ed8796"

[rust]
format = 'via [âš™ï¸ $version](#ed8796 bold)'

[swift]
format = 'via [ğŸ¦ $version](#ed8796 bold)'
